[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.71.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.71.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.71.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.71.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
[context.master.processing]
  skip_processing = false
[context.master.processing.css]
  bundle = true
  minify = true

 # /*
 #X-UA-Compatible : IE=edge
# Content-Type: text/html; charset=UTF-8; image/vnd.microsoft.icon ; application/json
# X-Frame-Options: DENY
# X-XSS-Protection: 1; mode=block
# Referrer-Policy: no-referrer
# X-Content-Type-Options: nosniff
# Content-Security-Policy: object-src 'none'; base-uri 'self'
# Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
[[plugins]]
  package = "netlify-plugin-inline-source"
[[plugins]]
package = "netlify-plugin-subfont"
[[plugins]]
  package = "netlify-plugin-minify-html"
