[context.production.environment]
HUGO_VERSION = "0.67.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.67.1"

[context.deploy-preview.environment]
HUGO_VERSION = "0.67.1"

# Default site wide settings
[build.processing]
  skip_processing = false

# Branch specific settings
[context.branch-name.processing]
  skip_processing = false

[context.branch-name.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls =  false

[build.processing.images]
  compress = false
