[context.production.environment]
HUGO_VERSION = "0.67.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.67.1"

[context.deploy-preview.environment]
HUGO_VERSION = "0.67.1"

# Default site wide settings
[build.processing]
  skip_processing = false

# Branch specific settings
[context.branch-name.processing]
  skip_processing = false

[context.branch-name.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls =  false

[build.processing.images]
  compress = false

#[[headers]]
 # for = "/*"
  #[headers.values]
  # Content-Type = "text/html; charset=UTF-8"
  # X-Content-Type-Options = "nosniff"
 #  X-UA-Compatible = "IE=edge;chrome=1"
  # X-Frame-Options = "DENY"
  # X-XSS-Protection = "1; mode=block"

   #Referrer-Policy = "strict-origin-when-cross-origin"
   #Content-Security-Policy = "object-src 'none'; base-uri 'self'"
   #Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"