[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.71.0"
  HUGO_ENABLEGITINFO = "true"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy-Report-Only = "default-src 'self' xenodochial-johnson-2c8705.netlify.app d33wubrfki0l68.cloudfront.net hyvor.com talk.hyvor.com cdnjs.cloudflare.com getsimpleform.com s3.amazonaws.com; form-action 'self' getsimpleform.com/; upgrade-insecure-requests; block-all-mixed-content"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Feature-Policy = '''
    ambient-light-sensor 'none';
    vibrate 'none';
    geolocation 'none';
    midi 'none';
    microphone 'none';
    camera 'none';
    magnetometer 'none';
    speaker 'none'
    unoptimised-images 'none'
    '''


[[headers]]
  for = "*.ico"
  [headers.values]
    Content-Type = "image/x-icon"
    Cache-Control = "max-age=604800, public"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"
    Cache-Control = "max-age=2628000, public"

[[headers]]
  for = "*.ttf"
  [headers.values]
    Content-Type = "font/ttf"
    Cache-Control = "max-age=2628000, public"

[[headers]]
  for = "*.otf"
  [headers.values]
    Content-Type = "font/otf"
    Cache-Control = "max-age=2628000, public"

[[headers]]
  for = "*.eot"
  [headers.values]
    Content-Type = "application/vnd.ms-fontobject"
    Cache-Control = "max-age=2628000, public"

[[headers]]
  for = "*.woff"
  [headers.values]
    Content-Type = "font/woff"
    Cache-Control = "max-age=2628000, public"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Content-Type = "font/woff"
    Cache-Control = "max-age=2628000, public"

[[headers]]
  for = "*.xml"
  [headers.values]
    Content-Type = "text/xml"
    Cache-Control = "max-age=3600, public"

[[headers]]
  for = "*.mp4"
  [headers.values]
    Content-Type = "video/mp4"
    Cache-Control = "max-age=604800, public"

[[headers]]
  for = "*.webm"
  [headers.values]
    Content-Type = "video/webm"
    Cache-Control = "max-age=604800, public"

[[headers]]
  for = "*.docx"
  [headers.values]
    Content-Type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    Cache-Control = "max-age=604800, public"

[[headers]]
  for = "*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Cache-Control = "max-age=604800, public"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "max-age=604800, public"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "max-age=604800, public"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "max-age=604800, public"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "max-age=604800, public"

[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "max-age=604800, public"


 # /*
 #X-UA-Compatible : IE=edge
# Content-Type: text/html; charset=UTF-8; image/vnd.microsoft.icon ; application/json
# X-Frame-Options: DENY
# X-XSS-Protection: 1; mode=block
# Referrer-Policy: no-referrer
# X-Content-Type-Options: nosniff
# Content-Security-Policy: object-src 'none'; base-uri 'self'
# Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
[[plugins]]
  package = "netlify-plugin-inline-source"
[[plugins]]
package = "netlify-plugin-subfont"
[[plugins]]
  package = "netlify-plugin-minify-html"
